version: '3.8'

services:
  database:
    image: postgres:16
    container_name: finance_database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=finance
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
